language: java
jdk: openjdk11

install:
  - ./gradlew --no-daemon assemble

script:
  - ./gradlew --no-daemon test

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

matrix:
  include:
    - jdk: openjdk11